create table if not exists users
(
    id          bigint primary key generated by default as identity,
    telegram_id bigint unique not null,
    username    varchar(255)  null,
    created_at  timestamp     not null
);

create table if not exists currencies
(
    id    bigint primary key generated by default as identity,
    code  varchar(3)     not null unique,
    name  varchar(50)    not null,
    value numeric(10, 2) not null check ( value > 0 )
);

create table if not exists exchange_rates
(
    id          bigint primary key generated by default as identity,
    value       numeric(10, 2) not null check ( value > 0 ),
    rate_date   timestamp      not null,
    currency_id bigint references currencies (id)
);

create table if not exists subscriptions
(
    id               bigint primary key generated by default as identity,
    is_active        boolean default false not null,
    last_notified_at timestamp             null,
    user_id          bigint,
    currency_id      bigint,
    unique (user_id, currency_id)
)
