spring:
  application:
    name: cbr-monitoring-spring
  datasource:
    password: cbr-monitoring
    username: cbr-monitoring
    url: jdbc:postgresql://localhost:6543/cbr-monitoring
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    open-in-view: false
  main:
    banner-mode: off
    web-application-type: none

business-logic:
  telegram:
    token: 8648306817:AAHyDUnp8NU-SnotFTPEPEnsrGZ7w-VN08M
    username: cbrMonitoringBot
  cbr-api:
    url: https://www.cbr-xml-daily.ru